# Generated by Django 5.1.6 on 2025-03-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("pk", "-created_at"),
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customers_c_created_1ed0f4_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customers_c_updated_7518c4_idx",
        ),
    ]
