# Generated by Django 5.1.6 on 2025-03-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
    ]
