# Generated by Django 5.1.6 on 2025-03-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_remove_customer_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
    ]
