# Generated by Django 5.1.6 on 2025-03-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="archived",
            field=models.BooleanField(
                db_default=None, default=False, verbose_name="Archived"
            ),
        ),
    ]
