# Generated by Django 5.1.6 on 2025-03-03 19:27

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service_product", "0003_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Contract Name"
                    ),
                ),
                (
                    "file_document",
                    models.FileField(
                        upload_to=contracts.models.create_directory_path_for_documents_customer,
                        verbose_name="Document file",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start date")),
                ("end_date", models.DateField(verbose_name="End date")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract",
                        to="service_product.product",
                        verbose_name="Service",
                    ),
                ),
            ],
        ),
    ]
