# Generated by Django 5.1.6 on 2025-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Cost"
            ),
            preserve_default=False,
        ),
    ]
