# Generated by Django 5.1.6 on 2025-03-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_cost"),
        ("service_product", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="service_product.product",
                verbose_name="Service",
            ),
        ),
    ]
