# Generated by Django 5.1.6 on 2025-03-06 13:53

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="file_document",
            field=models.FileField(
                upload_to=contracts.models.create_directory_path_for_documents_customer,
                verbose_name="File with documents",
            ),
        ),
    ]
