# Generated by Django 5.1.6 on 2025-03-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the promotion channel.",
                        max_length=100,
                        unique=True,
                        verbose_name="Channel Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the promotion channel.",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="adscompany",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ads.promotionchannel",
                verbose_name="Promotion channel",
            ),
        ),
    ]
