# Generated by Django 5.1.6 on 2025-03-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        ("leads", "0002_alter_lead_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="ads.adscompany",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Middle Name",
            ),
        ),
    ]
