# Generated by Django 5.1.6 on 2025-03-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_campaign_alter_lead_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
    ]
