# Generated by Django 5.1.6 on 2025-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("in_development", "In-Development"),
                ],
                default="inactive",
                max_length=20,
                verbose_name="Service status",
            ),
        ),
    ]
