# Generated by Django 5.1.6 on 2025-08-12 15:08

import django.db.models.deletion
import service_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_product", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=service_product.models.get_default_category,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="category",
                to="service_product.category",
                verbose_name="Category",
            ),
        ),
    ]
