# Generated by Django 5.1.6 on 2025-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_product", "0002_product_archived_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Service name"
            ),
        ),
    ]
